/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erhannis.fileselect;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 * //TODO Permit cancel
 * @author erhannis
 */
public class DFind<T extends Enum> extends javax.swing.JDialog {
    public static class Result<T extends Enum> {
        public String regex;
        public boolean recursive;
        public T value;

        public Result() {
            this("", false, null);
        }
        
        public Result(String regex, boolean recursive, T value) {
            this.regex = regex;
            this.recursive = recursive;
            this.value = value;
        }
    }
    
    private ComboBoxModel<T> ddModel;
    private Result<T> result;

    public DFind(java.awt.Frame parent, T[] options) {
        this(parent, options, new Result<T>());
    }

    /**
     * Creates new form DFind
     */
    public DFind(java.awt.Frame parent, T[] options, Result<T> result) {
        super(parent, true);
        this.result = result;
        ddModel = new DefaultComboBoxModel<T>(options);
        initComponents();
        tfRegex.setText(result.regex);
        cbRecursive.setSelected(result.recursive);
        ddEnum.setSelectedItem(result.value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfRegex = new javax.swing.JTextField();
        cbRecursive = new javax.swing.JCheckBox();
        ddEnum = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        bFindAndMark = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tfRegex.setToolTipText("Regex");
        tfRegex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRegexActionPerformed(evt);
            }
        });

        cbRecursive.setText("Recursive");

        ddEnum.setModel(ddModel);

        jLabel1.setText("Set to:");

        bFindAndMark.setText("Find and mark");
        bFindAndMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFindAndMarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfRegex)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddEnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbRecursive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(bFindAndMark)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfRegex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddEnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRecursive)
                    .addComponent(bFindAndMark))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfRegexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRegexActionPerformed
        bFindAndMarkActionPerformed(evt);
    }//GEN-LAST:event_tfRegexActionPerformed

    private void bFindAndMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFindAndMarkActionPerformed
        result.recursive = cbRecursive.isSelected();
        result.regex = tfRegex.getText();
        result.value = (T)ddEnum.getSelectedItem();
        this.dispose();
    }//GEN-LAST:event_bFindAndMarkActionPerformed

    public Result<T> go() {
        this.setVisible(true);
        return result;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFindAndMark;
    private javax.swing.JCheckBox cbRecursive;
    private javax.swing.JComboBox<T> ddEnum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfRegex;
    // End of variables declaration//GEN-END:variables
}
